#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	int goal = 0;
    while(true) {
        goal = (vexRT[Btn8U]) ? 2100 : goal; // high
        goal = (vexRT[Btn8R]) ? 2700 : goal; // middle
        goal = (vexRT[Btn8D]) ? 0 : goal; // low
        motor[port3] = -127 * (vexRT[Btn5U] - vexRT[Btn5D]);
        motor[port2] = 127 * (vexRT[Btn5U] - vexRT[Btn5D]);
        int pot = (SensorValue[potentiometer] < 1000) ? 3500 : SensorValue[potentiometer];
        motor[port1] = (goal == 0) ? 0 : ((pot - goal)/4.5);

    }
}
